---
- name:
  gather_facts: no
  hosts: nxos
  tasks:
    - name: Remove Vlan global
      nxos_vlan:
        vlan_id: "{{ vlan_id }}"
        state: absent
    
    - name: Remove Vlan from nve1
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: "{{ block_id }}{{ vlan_id }}"
        state: absent
    
    - name: Remove Vlan from evpn
      nxos_evpn_vni:
        vni: "{{ block_id }}{{ vlan_id }}"
        state: absent
    
    - name: Remove L3 Interface
      nxos_config:
        lines:
        - no interface Vlan{{ vlan_id }}
    
    - name: Save config
      nxos_command:
        commands:
        - copy running-config startup-config
...
