---
- name:
  gather_facts: no
  hosts: nxos
  tasks:
    - name: Create Vlan and map to VNI
      nxos_vlan:
        vlan_id: "{{ vlan_id }}"
        mapped_vni: "{{ block_id }}{{ vlan_id }}"
        name: "{{ description }}"
        state: present
      
    - name: Create Vlan and map to VNI
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: "{{ block_id }}{{ vlan_id }}"
        state: present
    
    - name: vni configuration
      nxos_evpn_vni:
        vni: "{{ block_id }}{{ vlan_id }}"
        route_distinguisher: auto
        route_target_both:
        - "{{ block_id }}:{{ block_id }}{{ vlan_id }}"
        state: present
    
    - name: Configure L3 Interface
      nxos_config:
        lines:
        - description {{ description }}
        - vrf member {{ vrf }}
        - ip address {{ ipv4 }} tag {{ vrf }}
        - fabric forwarding mode anycast-gateway
        - no shutdown
        parents: interface Vlan{{ vlan_id }}
    
    - name: Save config
      nxos_command:
        commands:
        - copy running-config startup-config

...
