---
- name:
  gather_facts: no
  hosts: nxos
  tasks:
    - name: Create Vlan and map to VNI
      nxos_vlan:
        vlan_id: "{{ vlan_id }}"
        mapped_vni: "{{ block_id }}{{ vlan_id }}"
        name: "{{ description }}"
        state: present
    
    - name: Create Vlan and map to VNI
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: "{{ block_id }}{{ vlan_id }}"
        state: present
    
    - name: vni configuration
      nxos_evpn_vni:
        vni: "{{ block_id }}{{ vlan_id }}"
        route_distinguisher: "{{ block_id }}:{{ vlan_id }}"
        route_target_both:
        - "{{ block_id }}:{{ vlan_id }}"
        state: present
    
    - name: Save config
      nxos_command:
        commands:
        - copy running-config startup-config
...
