--- 
- name: Create Vlan and map to VNI
  nxos_vlan:
    vlan_id: "{{ vxlan.vlan_id }}"
    mapped_vni: "{{ vxlan.fikz }}{{ vxlan.vlan_id }}"
    name: "{{ vxlan.description }}"
    state: present

- name: Create Vlan and map to VNI
  cisco.nxos.nxos_vxlan_vtep_vni:
    interface: nve1
    vni: "{{ vxlan.fikz }}{{ vxlan.vlan_id }}"
    state: present

- name: vni configuration
  cisco.nxos.nxos_evpn_vni:
    vni: "{{ vxlan.fikz }}{{ vxlan.vlan_id }}"
    route_distinguisher: "{{ vxlan.fikz }}:{{ vxlan.vlan_id }}"
    route_target_both:
    - "{{ vxlan.fikz }}:{{ vxlan.vlan_id }}"
    state: present

- name: Configure L3 Interface
  cisco.nxos.nxos_config:
    lines:
    - description {{ vxlan.description }}
    - vrf member {{ vxlan.vrf }}
    - ip address {{ vxlan.ipv4 }} tag {{ vxlan.vrf }}
    - fabric forwarding mode anycast-gateway
    parents: interface Vlan{{ vxlan.vlan_id }}

...